name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run:  source ./support/install-texlive.sh
    - run: l3build check -H -q
