name: CI

on: [push]

jobs:
  runs-on: ubuntu-latest
  check:
    name: Test
    steps:
    - uses: actions/checkout@v1
    - name: Cache TeX live
      uses: actions/cache@v1
      with:
        path: /tmp/texlive
        key: ${{ runner.OS }}-texlive
    - run:  source ./support/install-texlive.sh
    - name: Run tests
      run: |
           export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
           l3build check -q -H
  doc:
    name: Documentation
    steps:
    - uses: actions/checkout@v1
    - name: Cache TeX live
      uses: actions/cache@v1
      with:
        path: /tmp/texlive
        key: ${{ runner.OS }}-texlive
    - run:  source ./support/install-texlive.sh
    - name: Run tests
      run: |
           export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
           l3build doc -q

