name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache TeX live
      uses: actions/cache@v1
      with:
        path: /tmp/texlive
        key: ${{ runner.OS }}-texlive
        restore-keys: |
          ${{ runner.OS }}-texlive
    - run:  source ./support/install-texlive.sh
    - name: Cache TeX live again
      uses: actions/cache@v1
      with:
        path: /tmp/texlive
        key: ${{ runner.OS }}-texlive
        restore-keys: |
          ${{ runner.OS }}-texlive
    - run: |
           export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
           l3build check -q -H

